public class WebEx1_2_27 {
    public static void main (String[] args) {
    // One way to generate a random number taken from the Gaussian distribution is to use
    // the Box-Muller formula Z = sin(2 ¹ v) (-2 ln u)1/2where u and v and real numbers
    // between 0 and 1 generated by the Math.random() method. Write a program
    // StdGaussian.java that prints out a standard Gaussian random variable.
    double v = Math.random();
    double u = Math.random();
    double z = Math.sin(2*Math.PI*v) * (-2 * Math.log(u));
    System.out.print(z);
    }
}